name: upload artifacts to packagecloud

on:
  workflow_call:
    secrets:
      PACKAGECLOUD_TOKEN:
        required: true
    inputs:
      USERREPO:
        required: true
        type: string

jobs:

  upload-packagecloud:
    name: ${{ matrix.distro }} upload
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - distro: "ubuntu_latest"
            upload: ubuntu/jammy
          - distro: "debian_latest"
            upload: debian/bullseye

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
      - name: install
        run: |
          gem install package_cloud
          echo "PACKAGECLOUD_TOKEN=${{ secrets.PACKAGECLOUD_TOKEN }}" >> $GITHUB_ENV
      - name: upload
        run: |
          find results-${{ matrix.distro }}-* \( -name "*.deb" -o -name "*.dsc" \) | xargs -r package_cloud push ${{ inputs.USERREPO }}/${{ matrix.upload }}
